# Generated by Django 3.2.7 on 2021-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField()),
                ('ext', models.TextField(max_length=10)),
            ],
        ),
    ]
